version: '3.8'

services:
  backend:
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${ENV_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${ENV_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ENV_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - database

  frontend:
    image: "${DOCKER_USERNAME}/eventor-frontend:latest"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${ENV_DB_SCHEMA_NAME}
      MYSQL_USER: ${ENV_DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${ENV_DB_PASSWORD}
      MYSQL_PASSWORD: ${ENV_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

volumes:
  db_data:
